/*******************************************************************************
* File Name: cyfitter_gpio.h
* 
* PSoC Creator  4.4
*
* Description:
* 
* This file is automatically generated by PSoC Creator.
*
********************************************************************************
* Copyright (c) 2007-2020 Cypress Semiconductor.  All rights reserved.
* You may use this file only in accordance with the license, terms, conditions, 
* disclaimers, and limitations in the end user license agreement accompanying 
* the software package with which this file was provided.
********************************************************************************/

#ifndef INCLUDED_CYFITTER_GPIO_H
#define INCLUDED_CYFITTER_GPIO_H
#include "cy_device_headers.h"

/* S0 */
#define S0_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define S0_0_INBUF_ENABLED 0u
#define S0_0_INIT_DRIVESTATE 0u
#define S0_0_INIT_MUXSEL 0u
#define S0_0_INPUT_SYNC 2u
#define S0_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define S0_0_NUM 0u
#define S0_0_PORT GPIO_PRT9
#define S0_0_SLEWRATE CY_GPIO_SLEW_FAST
#define S0_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define S0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define S0_INBUF_ENABLED 0u
#define S0_INIT_DRIVESTATE 0u
#define S0_INIT_MUXSEL 0u
#define S0_INPUT_SYNC 2u
#define S0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define S0_NUM 0u
#define S0_PORT GPIO_PRT9
#define S0_SLEWRATE CY_GPIO_SLEW_FAST
#define S0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* S1 */
#define S1_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define S1_0_INBUF_ENABLED 0u
#define S1_0_INIT_DRIVESTATE 0u
#define S1_0_INIT_MUXSEL 0u
#define S1_0_INPUT_SYNC 2u
#define S1_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define S1_0_NUM 1u
#define S1_0_PORT GPIO_PRT9
#define S1_0_SLEWRATE CY_GPIO_SLEW_FAST
#define S1_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define S1_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define S1_INBUF_ENABLED 0u
#define S1_INIT_DRIVESTATE 0u
#define S1_INIT_MUXSEL 0u
#define S1_INPUT_SYNC 2u
#define S1_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define S1_NUM 1u
#define S1_PORT GPIO_PRT9
#define S1_SLEWRATE CY_GPIO_SLEW_FAST
#define S1_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* S2 */
#define S2_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define S2_0_INBUF_ENABLED 0u
#define S2_0_INIT_DRIVESTATE 0u
#define S2_0_INIT_MUXSEL 0u
#define S2_0_INPUT_SYNC 2u
#define S2_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define S2_0_NUM 2u
#define S2_0_PORT GPIO_PRT9
#define S2_0_SLEWRATE CY_GPIO_SLEW_FAST
#define S2_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define S2_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define S2_INBUF_ENABLED 0u
#define S2_INIT_DRIVESTATE 0u
#define S2_INIT_MUXSEL 0u
#define S2_INPUT_SYNC 2u
#define S2_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define S2_NUM 2u
#define S2_PORT GPIO_PRT9
#define S2_SLEWRATE CY_GPIO_SLEW_FAST
#define S2_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* S3 */
#define S3_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define S3_0_INBUF_ENABLED 0u
#define S3_0_INIT_DRIVESTATE 0u
#define S3_0_INIT_MUXSEL 0u
#define S3_0_INPUT_SYNC 2u
#define S3_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define S3_0_NUM 3u
#define S3_0_PORT GPIO_PRT9
#define S3_0_SLEWRATE CY_GPIO_SLEW_FAST
#define S3_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define S3_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define S3_INBUF_ENABLED 0u
#define S3_INIT_DRIVESTATE 0u
#define S3_INIT_MUXSEL 0u
#define S3_INPUT_SYNC 2u
#define S3_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define S3_NUM 3u
#define S3_PORT GPIO_PRT9
#define S3_SLEWRATE CY_GPIO_SLEW_FAST
#define S3_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Green */
#define Green_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Green_0_INBUF_ENABLED 0u
#define Green_0_INIT_DRIVESTATE 1u
#define Green_0_INIT_MUXSEL 3u
#define Green_0_INPUT_SYNC 2u
#define Green_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Green_0_NUM 1u
#define Green_0_PORT GPIO_PRT7
#define Green_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Green_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Green_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Green_INBUF_ENABLED 0u
#define Green_INIT_DRIVESTATE 1u
#define Green_INIT_MUXSEL 3u
#define Green_INPUT_SYNC 2u
#define Green_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Green_NUM 1u
#define Green_PORT GPIO_PRT7
#define Green_SLEWRATE CY_GPIO_SLEW_FAST
#define Green_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Button */
#define Button_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_0_INBUF_ENABLED 1u
#define Button_0_INIT_DRIVESTATE 0u
#define Button_0_INIT_MUXSEL 0u
#define Button_0_INPUT_SYNC 2u
#define Button_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_0_NUM 4u
#define Button_0_PORT GPIO_PRT0
#define Button_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Button_DRIVEMODE CY_GPIO_DM_HIGHZ
#define Button_INBUF_ENABLED 1u
#define Button_INIT_DRIVESTATE 0u
#define Button_INIT_MUXSEL 0u
#define Button_INPUT_SYNC 2u
#define Button_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Button_NUM 4u
#define Button_PORT GPIO_PRT0
#define Button_SLEWRATE CY_GPIO_SLEW_FAST
#define Button_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Mux_en */
#define Mux_en_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Mux_en_0_INBUF_ENABLED 0u
#define Mux_en_0_INIT_DRIVESTATE 0u
#define Mux_en_0_INIT_MUXSEL 0u
#define Mux_en_0_INPUT_SYNC 2u
#define Mux_en_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Mux_en_0_NUM 4u
#define Mux_en_0_PORT GPIO_PRT9
#define Mux_en_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Mux_en_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Mux_en_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Mux_en_INBUF_ENABLED 0u
#define Mux_en_INIT_DRIVESTATE 0u
#define Mux_en_INIT_MUXSEL 0u
#define Mux_en_INPUT_SYNC 2u
#define Mux_en_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Mux_en_NUM 4u
#define Mux_en_PORT GPIO_PRT9
#define Mux_en_SLEWRATE CY_GPIO_SLEW_FAST
#define Mux_en_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_rx */
#define UART_rx_0_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_0_INBUF_ENABLED 1u
#define UART_rx_0_INIT_DRIVESTATE 1u
#define UART_rx_0_INIT_MUXSEL 18u
#define UART_rx_0_INPUT_SYNC 2u
#define UART_rx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_0_NUM 0u
#define UART_rx_0_PORT GPIO_PRT5
#define UART_rx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_rx_DRIVEMODE CY_GPIO_DM_HIGHZ
#define UART_rx_INBUF_ENABLED 1u
#define UART_rx_INIT_DRIVESTATE 1u
#define UART_rx_INIT_MUXSEL 18u
#define UART_rx_INPUT_SYNC 2u
#define UART_rx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_rx_NUM 0u
#define UART_rx_PORT GPIO_PRT5
#define UART_rx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_rx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* UART_tx */
#define UART_tx_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_0_INBUF_ENABLED 0u
#define UART_tx_0_INIT_DRIVESTATE 1u
#define UART_tx_0_INIT_MUXSEL 18u
#define UART_tx_0_INPUT_SYNC 2u
#define UART_tx_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_0_NUM 1u
#define UART_tx_0_PORT GPIO_PRT5
#define UART_tx_0_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define UART_tx_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define UART_tx_INBUF_ENABLED 0u
#define UART_tx_INIT_DRIVESTATE 1u
#define UART_tx_INIT_MUXSEL 18u
#define UART_tx_INPUT_SYNC 2u
#define UART_tx_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define UART_tx_NUM 1u
#define UART_tx_PORT GPIO_PRT5
#define UART_tx_SLEWRATE CY_GPIO_SLEW_FAST
#define UART_tx_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Negative */
#define Negative_0_DRIVEMODE CY_GPIO_DM_ANALOG
#define Negative_0_INBUF_ENABLED 0u
#define Negative_0_INIT_DRIVESTATE 1u
#define Negative_0_INIT_MUXSEL 0u
#define Negative_0_INPUT_SYNC 2u
#define Negative_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Negative_0_NUM 1u
#define Negative_0_PORT GPIO_PRT10
#define Negative_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Negative_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Negative_DRIVEMODE CY_GPIO_DM_ANALOG
#define Negative_INBUF_ENABLED 0u
#define Negative_INIT_DRIVESTATE 1u
#define Negative_INIT_MUXSEL 0u
#define Negative_INPUT_SYNC 2u
#define Negative_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Negative_NUM 1u
#define Negative_PORT GPIO_PRT10
#define Negative_SLEWRATE CY_GPIO_SLEW_FAST
#define Negative_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

/* Positive */
#define Positive_0_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Positive_0_INBUF_ENABLED 0u
#define Positive_0_INIT_DRIVESTATE 1u
#define Positive_0_INIT_MUXSEL 0u
#define Positive_0_INPUT_SYNC 2u
#define Positive_0_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Positive_0_NUM 0u
#define Positive_0_PORT GPIO_PRT10
#define Positive_0_SLEWRATE CY_GPIO_SLEW_FAST
#define Positive_0_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS
#define Positive_DRIVEMODE CY_GPIO_DM_STRONG_IN_OFF
#define Positive_INBUF_ENABLED 0u
#define Positive_INIT_DRIVESTATE 1u
#define Positive_INIT_MUXSEL 0u
#define Positive_INPUT_SYNC 2u
#define Positive_INTERRUPT_MODE CY_GPIO_INTR_DISABLE
#define Positive_NUM 0u
#define Positive_PORT GPIO_PRT10
#define Positive_SLEWRATE CY_GPIO_SLEW_FAST
#define Positive_THRESHOLD_LEVEL CY_GPIO_VTRIP_CMOS

#endif /* INCLUDED_CYFITTER_GPIO_H */
